### ISSUE TITLE
Missing/Incorrect Functions

### ISSUE THREAD

**Issue by aers** [matortheeternal/xelib#1]
Was doing a quick port of this to C# so I could use it in my own project and noticed some errors.

Functions called in the JS side that are missing from the C side but do exist in the xedit-lib API:
GetElementGroup, SetIsEditable

Functions in the C side with incorrect definition:
RemoveElementOrParent has an extra argument
- definition in xedit-lib API: function RemoveElementOrParent(_id: Cardinal): WordBool; cdecl;
- definition here: WordBool(__cdecl* RemoveElementOrParent)(Cardinal, PWChar);

AddArrayItem on the JS side doesn't pass the id argument to the arrayItemContext helper in the error message.

SetElement on the JS side thinks SetElement returns a handle but the actual function doesn't.

**Comment by matortheeternal** [comment]
`GetElementGroup` added in e10e635

**Comment by matortheeternal** [comment]
`SetIsEditable` added in 945987e

**Comment by matortheeternal** [comment]
`RemoveElementOrParent` definition fixed in f3fd409

**Comment by matortheeternal** [comment]
`AddArrayItem` error message and `SetElement` invocation fixed in 8ac1cd1
